# Generated by Django 3.1.2 on 2020-10-06 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201006_0742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'permissions': (('can_mark_returned', 'Set book as returned'), ('can_view_books_borrowed', 'Can view books that are borrowed'))},
        ),
    ]
